### ISSUE TITLE
Droit  d'accès sur Pubby

### ISSUE THREAD

**Issue by krell** [krell/tg-elysium-xiii#1]
Je relève du mécontentement sur la politique de droit d'accès sur la map pubby dans le cadre des petites sessions.

Je peux vous proposer dans un premier temps de supprimer les départements inutiles.
Par exemple virer tout le cargo (je ferme tous les slots de job) et transférer leur responsabilité à l'ingénierie.

Mon objectif serait d'éviter que des joueurs choisissent de prendre hop et capitaine qui selon moi devrait être jouer dans un cadre HRP en toutes circonstance. J'aimerai entendre vos propositions de fusion de département pour rendre les sessions de jeu low pop plus agréable.

**Comment by Thrag-Zan** [comment]
Je réexpose en clair mon point de vue sur le souci des accès:

Lorsqu'une partie est lancée en ultra lowpop (généralement une personne isolée qui veux expérimenter) Ladite personne n'aura pas le choix que de chopper un poste capitaine , HoP pour avoir les accès nécessaire au lancement du SM , minage , Recherche de technologie.  Ou Hack toutes les portes en permanence. Dans les deux cas ce n’est pas une partie avec un fonctionnement normal.

C'est ce qui est arrivé ici : du monde s'est greffé a la session pour chill un peu . Ce qui fait qu'on s'est retrouvé avec un effectif un peu plus limite , ce qui pose souci c'est qu'on aient pas tous la même façon de voir la game.

Je proposerai plutôt un Game mode basique qui débloque les accès ces temps de jeu-là. Et quand l'effectif est suffisent (et la station bien rongée par les expérimentations) on pourrai relancer une partie normale.

Au moins tout le monde est d'accord sur le style de jeu qui règne sur la station.

**Comment by krell** [comment]
Je vois, je vais étudier la faisabilité de créer un gamemode appelé "openbar" et que les joueurs puissent voter pour ce style de session de jeu si cela convient à tout le monde.
