### ISSUE TITLE
Les petites ampoules se transforment en Néons

### ISSUE THREAD

**Issue by Thrag-Zan** [krell/tg-elysium-xiii#3]
## Description

Les petites ampoules se transforment en néons (néon brisé + changement de petite a grande fixture frame)
- Lorsque elles éclatent naturellement (a vérifier). 
- Lorsque elle sont brisées en frappant dessus

La petite fixture frame se transforme en grande lorsque l'on enleve une ampoule intacte a la main (testé éteinte)

**Comment by krell** [comment]
Je suis en train de faire la mise à jour du code tgstation, je vais en profiter pour corriger ce bug maintenant.

**Comment by krell** [comment]
C'est corrigé, j'embarque la modification dans la mise à jour d'aujourd'hui.
